###recuperar informacion

GET http://localhost:3000/pokemon/ditto
###para crear un pokemon

POST http://localhost:3000/pokemon/ditto
Content-type:application/json
 {
    "name":"ditto"
    "type":"normal"
    "moves":{
        "transform"
    }
 }